sudo: required

env:
  global:
    # for pip (--user)
    - PATH=$HOME/.local/bin:$PATH

services:
  - docker

language: generic

cache:
  directories:
  - $HOME/.nimline/
  - $HOME/.conda/

stages:
  - compile
  - test
  - deploy

notifications:
  slack:
    secure: GboTdvcsbPacYBE9XArFxryJdKwCXGPWGDDkgu1KgOc9R0rVvXfbPZ8WR4qEY/yeR/Dr7xphNazxB5mEfiloUjSbUeMTrdUafTQhXqNWJrSd88ZZ1DYN4EFmGCu3NXA1EjFdrP3zk2JOmldJtuAAg/Y4Th7kvmNyw2afR8LsCNEa2bVRZkJkTBhq9SJ9wNkhh4COlG0DMQK1sKPk613GuiTxB2tJNWWoueWv9tHoa+ZfRoG6PJKgumWl8uu3B5z6hSXc1byq9R6wya3CNOPcDmMFpM87D0fNWjg2+KxRfUEX6EQewG/PcUe2Wt54RYDzORMsv66N6sxi9Gv4mK8EKm3octTO330oWnyQflPfw2csPeYQ01d9+X2PmXXWiCf8SGNTqE5/BWCBxM5N5OVzTsrU9vL7LVecirtGPXWX1JshHVin7isi8i3uhAR7R6zddhHsMJesHj6Uqj79bBDPPZ5yWDoCtVsvGnclulc/uIGZmg96LX9v103iyGNWIyGvKj5oPeoxQQgnm+/APo1hJ53g/AHcmvBZhAgJs7SufWGq0ttacPFXWqNynKHSqY/Mu93LoZkgJUi5UDRjx7VyzREFHMTAj36hQPZvm8n/BmecoCwdUVVUu/RhmbzhGHhtNb+9o5cXpEJdqnz8k26wra/zFpFx2xlaSzk/4ZoIP10=

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

matrix:
  include:
  - stage: test
    name: "Linux Tests"
    os: linux
    script:
    - docker build -f Dockerfile -t nimline-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g` .
    - docker run --name test_nimline -t -u`id -u`:`id -g` nimline-test:latest nim cpp --cincludes:./tests -r nimline.nim
    - docker run --rm -t -u`id -u`:`id -g` nimline-test:latest nim cpp --cincludes:./tests -r --cc:clang nimline.nim
  - stage: test
    name: "macOS Tests"
    os: osx
    script:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    - export MACOSX_DEPLOYMENT_TARGET=10.13
    - conda create -n nimble_testing -c fragcolor nim=0.19.9.1
    - export PATH="$PATH:$HOME/miniconda/envs/nimline_testing/bin"
    - nim cpp --cincludes:./tests -r nimline.nim --nimcache:./nimcache
  # - stage: test
  #   name: "WASM Tests"
  #   os: linux
  #   script:
  #   - docker build -f Dockerfile -t nimline-test --build-arg USER_ID=`id -u` --build-arg GROUP_ID=`id -g`
  #   - docker run --rm -t -u`id -u`:`id -g` nimline-test:latest /bin/bash -c "source /etc/profile.d/emscripten.sh && nim cpp --d:wasm --cincludes:./tests -r nimline.nim"
